package com.example.gpsmapcamera.utils

import com.example.gpsmapcamera.BuildConfig
import java.util.Date

object Constants {

    val SAVED_DEFAULT_FILE_PATH="DCIM/Camera"
    val CUSTOM_SAVED_FILE_PATH_ROOT="DCIM/${BuildConfig.APPLICATION_ID}"
    val SAVED_FILE_NAME="${Date().formatForFile()}.jpg"




    const val FROM_TIME_ZONE = "FROM_TIME_ZONE"
    const val FROM_WEATHER_MODULE = "FROM_WEATHER_MODULE"
    const val FROM_TEMPERATURE_MODULE = "FROM_TEMPERATURE_MODULE"
    const val FROM_WIND_MODULE = "FROM_WIND_MODULE"
    const val FROM_PRESSURE_MODULE = "FROM_PRESSURE_MODULE"
    const val FROM_STAMP_POSITION = "FROM_STAMP_POSITION"
    const val FROM_STAMP_SIZE = "FROM_STAMP_SIZE"

    const val FROM_ALTITUDE = "FROM_ALTITUDE"
    const val FROM_ACCURACY = "FROM_ACCURACY"

    const val SELECTED_MAP_TYPE = "SELECTED_MAP_TYPE"
    const val SELECTED_MAP_POSITION = "SELECTED_MAP_POSITION"
    const val SELECTED_STAMP_POSITION = "SELECTED_STAMP_POSITION"
    const val SELECTED_STAMP_SIZE = "SELECTED_STAMP_SIZE"
    const val SELECTED_STAMP_FONT = "SELECTED_STAMP_FONT"
    const val SELECTED_MAP_ZOOM_LEVEL = "SELECTED_MAP_ZOOM_LEVEL"


    const val MAP_TYPE_SATELLITE = "MAP_TYPE_SATELLITE"
    const val MAP_TYPE_NORMAL = "MAP_TYPE_NORMAL"
    const val MAP_TYPE_TERRAIN = "MAP_TYPE_TERRAIN"
    const val MAP_TYPE_HYBRID = "MAP_TYPE_HYBRID"


    const val NUMBERING_PREFIX = "NUMBERING_PREFIX"
    const val NUMBERING_SUFFIX = "NUMBERING_SUFFIX"
    const val NUMBERING_SEQUENCE_NUMBER = "NUMBERING_SEQUENCE_NUMBER"
    const val NUMBERING_SEQUENCE_TYPE = "NUMBERING_SEQUENCE_TYPE"



    const val DATE_TIME_SELECTED_FORMAT = "DATE_TIME_SELECTED_FORMAT"
    const val TIME_ZONE_SELECTED_FORMAT = "TIME_ZONE_SELECTED_FORMAT"
    const val SELECTED_REPORTING_TAG = "SELECTED_REPORTING_TAG"
    const val SELECTED_NOTE = "SELECTED_NOTE"
    const val SELECTED_LAT_LONG = "SELECTED_LAT_LONG"
    const val SELECTED_PLUS_CODE = "SELECTED_PLUS_CODE"
    const val ADDED_PHONE_NUMBER = "ADDED_PHONE_NUMBER"

    const val SELECTED_STAMP_TEMPLATE = "SELECTED_STAMP_TEMPLATE"
    const val ADVANCE_TEMPLATE = "ADVANCE_TEMPLATE"
    const val CLASSIC_TEMPLATE = "CLASSIC_TEMPLATE"
    const val REPORTING_TEMPLATE = "REPORTING_TEMPLATE"
    const val PASSED_STAMP_TEMPLATE = "PASSED_STAMP_TEMPLATE"
    const val FROM_PLUS_CODE = "FROM_PLUS_CODE"


    const val FULL_ADDRESS_CITY = "FULL_ADDRESS_CITY"
    const val FULL_ADDRESS_STATE = "FULL_ADDRESS_STATE"
    const val FULL_ADDRESS_COUNTRY = "FULL_ADDRESS_COUNTRY"
    const val FULL_ADDRESS_PIN_CODE = "FULL_ADDRESS_PIN_CODE"




    const val KEY_REPORTING_TAG = "KEY_REPORTING_TAG"
    const val KEY_RECENT_NOTES = "KEY_RECENT_NOTES"
}